### ISSUE TITLE
Ability to change opacity from configure option in kde settings

### ISSUE THREAD

**Issue by Shaurya-Kalia** [yagomont/material-decoration-bt#1]
Is an option to change transparency going to be added in future or is it left to manually editing the theme? It would be quite convenient as well as simpler for newer users if an option is added

**Comment by yagomont** [comment]
I discovered my skillset is not enough to add a setting for translucency. In fact, I never saw any one else other than Breeze making something more than a button size selector. So, this is partially out of my scope.

However, you can now call bt-opacity from a terminal to change the opacity while running. That is, if you install through the new installer, since it does require some setting up now. Thankfully, everything is automatic now.

Feel free to test it out.

**Comment by yagomont** [comment]
Alright, finished polishing it up and testing.

**Comment by Shaurya-Kalia** [comment]
> I discovered my skillset is not enough to add a setting for translucency. In fact, I never saw any one else other than Breeze making something more than a button size selector. So, this is partially out of my scope.
> 
> However, you can now call bt-opacity from a terminal to change the opacity while running. That is, if you install through the new installer, since it does require some setting up now. Thankfully, everything is automatic now.
> 
> Feel free to test it out.

Well, changing it from terminal is enough for me. However if you want to have a look at a theme with multiple configuration options under kde settings, check [Seirra-breeze-enhanced](https://github.com/kupiqu/SierraBreezeEnhanced)

**Comment by yagomont** [comment]
Hey, thanks. I'll have a look, and maybe implement it if I have the time. For now, the terminal method is more than enough for me.
